version: "3"
networks:
    mynetwork:
      driver: bridge
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: chavis
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: rest_db
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    networks:
      - mynetwork

  app:
    build: .
    command: go run main.go
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - mynetwork
  
